/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    fontFamily: {
      "sans": ["Manrope", "sans-serif"],
    },
    colors: {
      "transparent": "transparent",
      "current": "currentColor",
      "white": "#ffffff",
      "black": "#000000",
      "tertiary": "#ac2452",
      "surface-container-low": "#f3f4f5",
      "surface-container-high": "#e7e8e9",
      "on-secondary-fixed": "#002106",
      "inverse-primary": "#5ae070",
      "surface-bright": "#f8f9fa",
      "inverse-on-surface": "#f0f1f2",
      "inverse-surface": "#2e3132",
      "primary-container": "#008731",
      "on-primary-fixed-variant": "#00531b",
      "surface-variant": "#e1e3e4",
      "outline": "#6d7b6b",
      "error-container": "#ffdad6",
      "tertiary-fixed": "#ffd9df",
      "surface-container-lowest": "#ffffff",
      "on-tertiary-container": "#fffbff",
      "surface": "#f8f9fa",
      "on-secondary": "#ffffff",
      "surface-dim": "#d9dadb",
      "secondary": "#346a39",
      "on-primary-fixed": "#002106",
      "primary": "#006b25",
      "surface-container": "#edeeef",
      "on-secondary-fixed-variant": "#1b5124",
      "on-tertiary-fixed": "#3f0017",
      "on-surface-variant": "#3d4a3c",
      "on-surface": "#191c1d",
      "on-primary": "#ffffff",
      "primary-fixed-dim": "#5ae070",
      "on-secondary-container": "#396e3d",
      "on-error-container": "#93000a",
      "primary-fixed": "#78fd89",
      "on-error": "#ffffff",
      "secondary-fixed": "#b6f1b4",
      "secondary-container": "#b3eeb1",
      "surface-container-highest": "#e1e3e4",
      "outline-variant": "#bccbb8",
      "secondary-fixed-dim": "#9ad59a",
      "tertiary-fixed-dim": "#ffb1c0",
      "on-tertiary": "#ffffff",
      "tertiary-container": "#cd3f6a",
      "on-primary-container": "#f7fff2",
      "on-background": "#191c1d",
      "surface-tint": "#006e26",
      "error": "#ba1a1a",
      "background": "#f8f9fa",
      "on-tertiary-fixed-variant": "#8f053d"
    },
    extend: {
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      }
    },
  },
  plugins: [],
}
